/** @format */

//export const API_URL = 'http://192.168.3.35:8080/apipedidosprofit2kdoce'
//export const API_URL = 'http://localhost/apipedidosprofit2kdoce'
export const API_URL = 'http://asatvicos.ddns.net:8080/apiPedidosProfit2kdoce'
export const API_URL_LICENCE = 'https://estudio57.net/apilicenciasweb/api'
//export const API_URL = 'https://react-native-ecommerce-dev.herokuapp.com'

export const TOKEN = 'token'
export const SEARCH_HISTORY = 'search-history'
export const SEARCH_HISTORY_CLIENT = 'search-history-client'
export const CART = 'cart'
export const ARTICULOS = 'saArticulo'
export const PRECIOS = 'saArtPrecio'
export const UNIDAD = 'saArtUnidad'
export const STOCK = 'saArtStock'
export const CLIENT = 'client'
export const CLIENTES = 'saCliente'
export const SUCURSAL = '01'
export const ALMACEN = 'CEDIS'
export const MONEDA = '$'
export const DB = 'SATVICOS_A'
export const TASA = 'tasa'
export const PEDIDOS = 'saPedidosVenta'
export const TRANSPORTE = 'saTransporte'
export const FORMA_PAGO = 'saFormaPago'
export const FECHA_VENCIMIENTO = new Date(2021, 12, 31)
export const FECHA_ACTUAL = new Date()
export const STRAPI_PUBLISHABLE_KEY =
	'pk_test_51IGQJXFotiOk2WnmTOM6HpcPnfjZSX98o9FqA5RJiMKB6jm62hiVu7mtk9rxgMjPSbjdIJxGmN6jwFNQ69IQ7f9O00AthydrqM'
export const DATOS_LICENCIA = 'serial'
export const ID_EMPRESA = 'id_empresa'
export const FECHA_VALIDEZ = 'fecha_validez'
export const FECHA_ACTIVACION = 'fecha_activacion'
export const SERIAL_APP = 'fll7xckytcyjuvzlie08t2yhs3cqqguvx3jj7v1a6miy35pb3q'
